# Site
name: "Tools. Docs. Thoughts."
title: "Tools. Docs. Thoughts."
description: "Writing and tooling on cybersecurity, open source, and technical communication."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: "" # Leave empty for GitHub Pages root-level site
google_analytics: "" # Add your own ID if needed
disqus: "" # Disable for now
include: ["_pages"]
permalink: /:title/

# Author (minimal placeholder for now)
authors:
  broen:
    name: Broen
    display_name: Broen
    avatar: 'assets/images/avatar.png'
    description: "Security-minded engineer writing clearly for humans."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Markdown engine
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Disable Adsense and lazy images
adsense: "disabled"
lazyimages: "disabled"

# Exclude files from build
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
